namespace: inventario-dev
images:
  - name: harbor.coopetarrazu.com:8443/ms-articulo-compose
    newName: harbor.coopetarrazu.com:8443/cluster/dev/articulos/ms-articulos
    newTag: v1.0.1
resources:
  - ../../base